<?php
/**
 * @file
 * Drupal integration for conduit.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * @mainpage Conduit Drupal
 * Conduit Drupal provides Drupal integration for Conduit.
 *
 * For information on the Drupal specific job properties see the perform
 * functions on the following plugins.
 * - @link plumbing_perform Plumbing @endlink.
 * - @link scan_perform Scan @endlink.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function conduit_drupal_ctools_plugin_directory($module, $plugin) {
  if (($module == 'worker' && $plugin == 'worker') || ($module == 'conduit' && $plugin == 'server')) {
    return 'plugins/' . $plugin;
  }
}
